CRM_ID/urls.py
from django.contrib import admin
from django.urls import path, include

from apps.common.views import *
from apps.leads.views import *
from apps.clients.views import *
from django.contrib.auth import views as auth_views
from apps.ideabox.views import *
from apps.wpmessages.views import *
from apps.userprofile.views import preview_template

urlpatterns = [

    path('admin/', admin.site.urls),
    
    path('', HomeView.as_view(), name='home'),
    path('home/', HomeView.as_view(), name='home'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),

    path('profile-update/', ProfileUpdateView.as_view(), name='profile-update'),
    path('profile/', ProfileView.as_view(), name='profile'),

    # Authentication 
    # path('register/', SignUpView.as_view(), name="register"),

    path('login/', auth_views.LoginView.as_view(
        template_name='common/login.html'
        ),
        name='login'
    ),

    path('logout/', auth_views.LogoutView.as_view(
        next_page='home'
        ),
        name='logout'
    ),

    path(
        'change-password/',
        auth_views.PasswordChangeView.as_view(
            template_name='common/change-password.html',
            success_url='/'
        ),
        name='change-password'
    ),

    # Forget Password
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='common/password-reset/password_reset.html',
             subject_template_name='common/password-reset/password_reset_subject.txt',
             email_template_name='common/password-reset/password_reset_email.html',
             # success_url='/login/'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='common/password-reset/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='common/password-reset/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='common/password-reset/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    
    #LEADS
    path('leads/',LeadsView.as_view(), name='leads'),  
    path('update_lead/<int:pk>/', LeadUpdateView.as_view(), name='update_lead'),
    path('delete_lead/<int:pk>/', LeadDeleteView.as_view(), name='delete_lead'),
    path('add_lead/', AddLeadView.as_view(), name='add_lead'),
    path('lead_info/<int:pk>/', LeadDetailView.as_view(), name='lead_info'),
    path('delete_followup/<int:pk>/', FollowUpDeleteView.as_view(), name='delete_followup'),
    
    #CLIENTS
    path('clients/',ClientsView.as_view(), name='clients'),
    path('update_client_status_listview/<int:pk>/', update_client_status_listview, name='update_client_status_listview'),
    path('update_client_status_client_info/<int:pk>/', update_client_status_client_info, name='update_client_status_client_info'),
    path('client_info/<int:pk>/', ClientDetailView.as_view(), name='client_info'),
    path('update_client/<int:pk>/', ClientUpdateView.as_view(), name='update_client'),
    path('delete_client/<int:pk>/', ClientDeleteView.as_view(), name='delete_client'),
    path('add_client/', AddClientView.as_view(), name='add_client'),
    path('migrate_client_lead/<int:pk>/', MigrateClientLeadView.as_view(), name='migrate_client_lead'),
     
    #IDEABOX
    path('submit_suggestion/', SubmitSuggestionView.as_view(), name='submit_suggestion'),
    path('suggestions/', SuggestionsListView.as_view(), name='suggestions_list'),
    path('update_suggestion/<int:pk>/', SuggestionUpdateView.as_view(), name='view_suggestion'),
    path('preview/', preview_template, name='index'),

    #MESSAGES
    path('messages/', WpMessagesView.as_view(), name='wpmessages'),
    path('f2ebd9bb-3e10-494b-80d1-45a7b5a11d02/', whatsapp_webhook, name='whatsapp-webhook'),
    path('update_contacted_status/<int:wpmessage_id>/', update_contacted_status, name='update_contacted_status'),
    path('delete_wpmessage/<int:pk>/', DeleteWpMessageView.as_view(), name='delete_wpmessage'),
    path('migrate_to_leads/<int:pk>/', MigrateToLeadView.as_view(), name='migrate_to_leads'),

    #VISUAL ADMIN
    path('chatbot/', include('apps.visualadmin.urls')),

]


from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/userprofile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    phone_number = models.CharField(max_length=12, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    profile_image = models.ImageField(default='default-avatar.png', upload_to='users/', null=True, blank=True)

    def __str__(self):
        return '%s %s' % (self.user.first_name, self.user.last_name)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

templates/base.html
{% load static %}
{% load crispy_forms_tags %}
{% load custom_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>CRM - IMPACTAR DIGITAL</title>

  <!-- Custom fonts for bootstrap-->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <!-- Custom fonts Google Material Icons (Using this) -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">  
  <!-- Custom styles Custom2 Css-->
  <link rel="stylesheet" href="{% static 'css/custom2.css' %}">

  <!-- Apply the saved theme immediately to avoid flicker -->
  <script>
    (function() {
        const savedTheme = localStorage.getItem('theme');
        if (savedTheme === 'dark') {
            document.documentElement.classList.add('dark-theme-variables');
        }
    })();
  </script> 

</head>

<body id="page-top">
    <div class="container"> 
        <aside>
            <div class="top">
                <div class="logo">
                    <img src="{% static 'img/LOGO_ID.png' %}">
                    <h2><span class="orange-id" id="imapactar">IMPACTAR </span><span class="blue-id">DIGITAL</span>
                </div>
                <div class="close" id="close-btn">
                    <span class="material-icons">close</span>
                </div>
            </div>
            <div class="sidebar">
                <a href="{% url 'dashboard' %}" class="{% active_url request 'dashboard' %}">
                    <span class="material-icons">grid_view</span>
                    <h3>Dashboard</h3>
                </a>
                <a href="{% url 'clients' %}" class="{% active_url request 'clients' %}">
                    <span class="material-icons">groups</span>
                    <h3>Clients</h3>
                </a>
                <a href="{% url 'leads' %}" class="{% active_url request 'leads' %}">
                    <span class="material-icons">reduce_capacity</span>
                    <h3>Leads</h3>
                </a>
                <a href="{% url 'wpmessages' %}" class="{% active_url request 'wpmessages' %}">
                    <span class="material-icons">mail_outline</span>
                    <h3>Messages</h3>
                    <span class="message-count">{{ message_count }}</span>
                </a>
                <a href="{% url 'visualadmin' %}" class="{% active_url request 'visualadmin' %}">
                    <span class="material-icons">smart_toy</span>
                    <h3>Chatbot Questions</h3>
                </a>
                <a href="{% url 'profile' %}" class="{% active_url request 'profile' %}">
                    <span class="material-icons">person_outline</span>
                    <h3>Profile</h3>
                </a>
                <a href="{% url 'change-password' %}" class="{% active_url request 'change-password' %}">
                    <span class="material-icons">key</span>
                    <h3>Change Password</h3>
                </a>
                <a href="{% url 'suggestions_list' %}" class="{% active_url request 'suggestions_list' %}">
                    <span class="material-icons">lightbulb</span>
                    <h3>Idea Box</h3>
                </a>
                <div class="logout-container">
                    <a class="nav-link" href="#" onclick="document.getElementById('logout-form').submit();">
                        <span class="material-icons">logout</span>
                        <h3>Logout</h3>
                    </a>
                    <form id="logout-form" action="{% url 'logout' %}" method="post" style="display: none;">
                        {% csrf_token %}
                    </form>
                </div>
            </div>
        </aside>
        <main>
            <!-- MAIN SESSION HERE -->
            {% include 'common/messages.html' %}

            {% block content %}  
            
            {% endblock content %}
        </main>
        <!-- RIGHT SESSION HERE -->
        <div class="right">
            <!-- BEGIN OF TOP BAR -->
            <div class="top">
                <button id="menu-btn">
                    <span class="material-icons">menu</span>
                </button>
                <div class="theme-toggler">
                    <span class="material-icons active">light_mode</span>
                    <span class="material-icons">dark_mode</span>
                </div>
                <div class="profile">
                    <div class="info">
                        <p>Welcome, <b>{{ user.first_name }} {{ user.last_name }}</b>!</p>
                    </div>
                    <div class="profile-photo">
                        <img src="{{user.profile.profile_image.url}}" alt="Profile Photo">
                        <small class="text-muted">{{ user.username }}</small>
                    </div>
                </div>
            </div>
            <!-- END OF TOP BAR -->
        </div>
  </div>
  
{% block script %}

  <!-- JavaScript e outros scripts essenciais -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <script src="{% static 'js/custom.js' %}"></script>
  
  <script>
    $(document).ready(function() {
        setTimeout(function() {
            $('#msg').fadeOut('slow', function() {
                $(this).remove();
            });
        }, 2000);
    });
  </script>

{% endblock script %}

{% block extra_css %} 
<!-- Custom CSS específicos para certas páginas podem ser adicionados aqui -->

<link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">

{% endblock extra_css %}
{% block extra_js %}{% endblock %}

</body>
</html>

templates/base_table.html
{% load static %}
{% load crispy_forms_tags %} 
<!DOCTYPE html>
<html lang="en">

<head>
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Django CRM Project</title>

  <!-- Custom fonts for this template-->
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.0/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.7.2/font/bootstrap-icons.min.css" rel="stylesheet">
  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

  <!-- Date Time Picker CSS -->
  <link rel="stylesheet" href="{% static 'date-time-phone/jquery-ui.css' %}">
  <link rel='stylesheet' href="{% static 'date-time-phone/jquery-ui-timepicker-addon.css' %}" />
  <!-- Date Time Picker CSS -->
</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" style="margin: 10px;" href="#">
        <div class="sidebar-brand-icon">
          <i class="fas fa-address-card"></i>
          <!-- <img src="{% static 'img/ID-logo.png' %}" class="sidebar-logo" > -->
        </div>
          <div class="sidebar-brand-text mx-3"> <sup>CRM - Impactar Digital</sup></div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <p class="text-center text-white font-weight-bold">Welcome {{user.first_name}} {{user.last_name}}!</p>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'dashboard' %}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - LEADS -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'leads' %}">
          <i class="fas fa-fw fa-chart-area"></i>
          <span>Leads</span></a>
      </li>

      <!-- Nav Item - CLIENTS -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'clients' %}">
          <i class="fas fa-fw fa-table"></i>
          <span>Clientes</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Profile -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'profile' %}">
          <i class="fas fa-fw fa-user"></i>
          <span>Profile</span></a>
      </li>

      <!-- Nav Item - Change Password -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'change-password' %}">
          <i class="fas fa-fw fa-key"></i>
          <span>Change Password</span></a>
      </li>

      <!-- Nav Item - Logout -->
      <li class="nav-item">
        <form action="{% url 'logout' %}" method="post">
          {% csrf_token %}
          <button type="submit" class="btn btn-link nav-link" style="color: white; text-decoration: none;">
            <i class="fas fa-fw fa-sign-out-alt"></i>
            <span>Logout</span>
          </button>
        </form>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        {% include 'common/messages.html' %}

        {% block content %}  
        
        {% endblock content %}
        
      </div>
      <!-- End of Main Content -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  {% block script %}
  <!-- Scripts específicos para certas páginas podem ser adicionados aqui -->

  {% endblock script %}
  
  {% block extra_css %} 
  <!-- Custom CSS específicos para certas páginas podem ser adicionados aqui -->
  
  <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
  
  {% endblock extra_css %}

    <!-- Bootstrap core JavaScript e outros scripts essenciais -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

    <!-- Scripts de plugins podem ser carregados aqui ou em páginas específicas se não forem usados globalmente -->
    <script src="{% static 'date-time-phone/jquery-ui.js' %}"></script>
    <script src="{% static 'date-time-phone/jquery-ui-timepicker-addon.js' %}"></script>
    <script src="{% static 'date-time-phone/jquery-input-mask-phone-number.min.js' %}"></script>

    <script>
        $(document).ready(function() {
            $('#id_phone_number').setupPhoneMaskOnField({
                format: '(xx) xxxx-xxxx',
            });
            $('#id_birth_date').datepicker({
                dateFormat: 'yy-mm-dd'
            }).attr("autocomplete", "off");
            setTimeout(function() {
                if ($('#msg').length > 0) {
                    $('#msg').remove();
                }
            }, 2000);
        });
    </script>
</body>
</html>

templates/index.html
{% load static %}
{% load crispy_forms_tags %} 
<!DOCTYPE html>

<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>CRM - IMPACTAR DIGITAL</title>

  <!-- Custom fonts for bootstrap-->
 
  <!-- Custom fonts Google Material Icons (Using this) -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">  <!-- Custom styles Custom2 Css-->
  <link rel="stylesheet" href="{% static 'css/custom2.css' %}">

  <!-- Date Time Picker CSS -->
  <link rel="stylesheet" href="{% static 'date-time-phone/jquery-ui.css' %}">
  <link rel='stylesheet' href="{% static 'date-time-phone/jquery-ui-timepicker-addon.css' %}"/>
  <!-- Date Time Picker CSS -->
  
</head>
<body id="page-top">
    <div class="container"> 
        <aside>
            <div class="top">
                <div class="logo">
                    <img src="{% static 'img/LOGO_ID.png' %}">
                    <h2><span class="orange-id">IMPACTAR </span><span class="blue-id">DIGITAL</span>
                </div>
                <div class="close" id="close-btn">
                    <span class="material-icons">close</span>
                </div>
            </div>
            {% if request.user == suggestion.user or request.user.is_superuser %}
            <div class="sidebar">
                <a href="{% url 'dashboard' %}" >
                    <span class="material-icons">grid_view</span>
                    <h3>Dashboard</h3>
                </a>
                <a href="{% url 'clients' %}">
                    <span class="material-icons">groups</span>
                    <h3>Clients</h3>
                </a>
                <a href="{% url 'leads' %}">
                    <span class="material-icons">reduce_capacity</span>
                    <h3>Leads</h3>
                </a>
                <a href="#">
                    <span class="material-icons">mail_outline</span>
                    <h3>Messages</h3>
                    <span class="message-count">26</span>
                </a>
                <a href="{% url 'profile' %}">
                    <span class="material-icons">person_outline</span>
                    <h3>Profile</h3>
                </a>
                <a href="{% url 'change-password' %}">
                    <span class="material-icons">key</span>
                    <h3>Change Password</h3>
                </a>
                <a href="{% url 'suggestions_list' %}">
                    <span class="material-icons">lightbulb</span>
                    <h3>Idea Box</h3>
                <div class="logout-container">
                    <a class="nav-link" href="#" onclick="document.getElementById('logout-form').submit();">
                        <span class="material-icons">logout</span>
                        <h3>Logout</h3>
                    </a>
                    <form id="logout-form" action="{% url 'logout' %}" method="post" style="display: none;">
                        {% csrf_token %}
                    </form>
                </div>
            </div>
            {% endif %}
        </aside>
        <main>
        <!-- MAIN CONTENT HERE I MAY HAVE TO MOVE THE BLOCK CONTENT HERE --> 
        </main>
        <!-- RIGHT SESSION IF NEEDED -->
        <div class="right">
            <!-- BEGIN OF TOP BAR -->
            <div class="top">
                <button id="menu-btn">
                    <span class="material-icons">menu</span>
                </button>
                <div class="theme-toggler">
                    <span class="material-icons active">light_mode</span>
                    <span class="material-icons">dark_mode</span>
                </div>
                <div class="profile">
                    <div class="info">
                        <p>Welcome, <b>{{user.first_name}} {{user.last_name}}!</b></p>
                        <small class="text-muted">{{user.user_name}}</small>
                    </div>
                    <div class="profile-photo">
                        <img src="{% static 'img/LOGO_ID.png' %}">
                    </div>
                </div>
            </div>
            <!-- END OF TOP BAR -->
        </div>
    </div>    
<!-- Content Wrapper -->
<div id="content-wrapper" class="d-flex flex-column">

    <!-- Main Content -->
    <div id="content">

      {% include 'common/messages.html' %}

      {% block content %}  
      
      {% endblock content %}
      
    </div>
    <!-- End of Main Content -->

  </div>
  <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

{% block script %}
  <!-- Bootstrap core JavaScript e outros scripts essenciais -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>
  <script src="{% static 'date-time-phone/jquery-ui-timepicker-addon.js' %}"></script>
  <script src="{% static 'date-time-phone/jquery-input-mask-phone-number.min.js' %}"></script>
  <script src="{% static 'js/custom.js' %}"></script>
  <script>
    $(document).ready(function() {
      
        setTimeout(function() {
          $('#msg').fadeOut('slow', function() {
              $(this).remove();
          });
      }, 2000);
    }); 
  </script>
{% endblock script %}

{% block extra_css %} 
<!-- Custom CSS específicos para certas páginas podem ser adicionados aqui -->

<link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">

{% endblock extra_css %}

</body>
</html>

templates/index_init.html
{% load static %}
<!DOCTYPE html>

<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>CRM - IMPACTAR DIGITAL</title>

  <!-- Custom fonts for bootstrap-->
 
  <!-- Custom fonts Google Material Icons (Using this) -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">  <!-- Custom styles Custom2 Css-->
  <link rel="stylesheet" href="{% static 'css/custom2.css' %}">
  <!-- Date Time Picker CSS -->
  <link rel="stylesheet" href="{% static 'date-time-phone/jquery-ui.css' %}">
  <link rel='stylesheet' href="{% static 'date-time-phone/jquery-ui-timepicker-addon.css' %}"/>
  <!-- Date Time Picker CSS -->
</head>

<body id="page-top">
    <div class="container"> 
        <aside>
            <div class="top">
                <div class="logo">
                    <img src="{% static 'img/LOGO_ID.png' %}">
                    <h2><span class="orange-id">IMPACTAR </span><span class="blue-id">DIGITAL</span>
                </div>
                <div class="close" id="close-btn">
                    <span class="material-icons">close</span>
                </div>
            </div>
            {% if request.user == suggestion.user or request.user.is_superuser %}
            <div class="sidebar">
                <a href="{% url 'dashboard' %}" >
                    <span class="material-icons">grid_view</span>
                    <h3>Dashboard</h3>
                </a>
                <a href="{% url 'clients' %}">
                    <span class="material-icons">groups</span>
                    <h3>Clients</h3>
                </a>
                <a href="{% url 'leads' %}">
                    <span class="material-icons">reduce_capacity</span>
                    <h3>Leads</h3>
                </a>
                <a href="#">
                    <span class="material-icons">mail_outline</span>
                    <h3>Messages</h3>
                    <span class="message-count">26</span>
                </a>
                <a href="{% url 'profile' %}">
                    <span class="material-icons">person_outline</span>
                    <h3>Profile</h3>
                </a>
                <a href="{% url 'change-password' %}">
                    <span class="material-icons">key</span>
                    <h3>Change Password</h3>
                </a>
                <a href="{% url 'suggestions_list' %}">
                    <span class="material-icons">lightbulb</span>
                    <h3>Idea Box</h3>
                <div class="logout-container">
                    <a class="nav-link" href="#" onclick="document.getElementById('logout-form').submit();">
                        <span class="material-icons">logout</span>
                        <h3>Logout</h3>
                    </a>
                    <form id="logout-form" action="{% url 'logout' %}" method="post" style="display: none;">
                        {% csrf_token %}
                    </form>
                </div>
            </div>
            {% endif %}
        </aside>
        <main>
        <!-- MAIN CONTENT HERE I MAY HAVE TO MOVE THE BLOCK CONTENT HERE --> 
        </main>
        <!-- RIGHT SESSION IF NEEDED -->
        <div class="right">
            <!-- BEGIN OF TOP BAR -->
            <div class="top">
                <button id="menu-btn">
                    <span class="material-icons">menu</span>
                </button>
                <div class="theme-toggler">
                    <span class="material-icons active">light_mode</span>
                    <span class="material-icons">dark_mode</span>
                </div>
                <div class="profile">
                    <div class="info">
                        <p>Welcome, <b>{{user.first_name}} {{user.last_name}}!</b></p>
                        <small class="text-muted">{{user.user_name}}</small>
                    </div>
                    <div class="profile-photo">
                        <img src="{% static 'img/LOGO_ID.png' %}">
                    </div>
                </div>
            </div>
            <!-- END OF TOP BAR -->
        </div>
    </div>    
<!-- Content Wrapper -->
<div id="content-wrapper" class="d-flex flex-column">

    <!-- Main Content -->
    <div id="content">

      {% include 'common/messages.html' %}

      {% block content %}  
      
      {% endblock content %}
      
    </div>
    <!-- End of Main Content -->

  </div>
  <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

{% block script %}
  <!-- Bootstrap core JavaScript e outros scripts essenciais -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>
  <script src="{% static 'date-time-phone/jquery-ui-timepicker-addon.js' %}"></script>
  <script src="{% static 'date-time-phone/jquery-input-mask-phone-number.min.js' %}"></script>
  <script src="{% static 'js/custom.js' %}"></script>
  <script>
    $(document).ready(function() {
      
        setTimeout(function() {
          $('#msg').fadeOut('slow', function() {
              $(this).remove();
          });
      }, 2000);
    }); 
  </script>
{% endblock script %}

{% block extra_css %} 
<!-- Custom CSS específicos para certas páginas podem ser adicionados aqui -->

<link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">

{% endblock extra_css %}

</body>
</html>